Parameters:
  AlarmName:
    Type: String
    Default: telegram-bot-alarm
    Description: Name of alarm
  LambdaFunctionName:
    Type: String
    Description: Lambda function name
  SNSTopicName:
    Type: String
    Default: telegram-bot-alarms
    Description: SNS topic name
  EmailRecipient:
    Type: String
    Description: Email recipient

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      FifoTopic: false
      Subscription:
        - Endpoint: !Ref EmailRecipient
          Protocol: email
      TopicName: !Ref SNSTopicName

  CloudWatchAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Fn::Join:
            - ":"
            - - arn:aws:sns
              - !Ref AWS::Region
              - !Ref AWS::AccountId
              - !Ref SNSTopicName
      AlarmDescription: Telegram bot email notifications for any errors on Lambda
      AlarmName: !Ref AlarmName
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionName
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: SampleCount
      Threshold: 0
      TreatMissingData: missing
