name: deploy-aws-lambda
on:
  push:
    branches:
      - test
      - prod
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18"]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy test
        if: ${{ github.ref == 'refs/heads/test'}}
        run: npm run-script deploy-test
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN_TEST }}
          CSE_ID: ${{ secrets.CSE_ID }}
          GOOGLE_API: ${{ secrets.GOOGLE_API }}
          OPENWEATHER_API: ${{ secrets.OPENWEATHER_API }}
      - name: Deploy prod
        if: ${{ github.ref == 'refs/heads/prod'}}
        run: npm run-script deploy-prod
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN_PROD }}
          CSE_ID: ${{ secrets.CSE_ID }}
          GOOGLE_API: ${{ secrets.GOOGLE_API }}
          OPENWEATHER_API: ${{ secrets.OPENWEATHER_API }}
