name: pulumi
on:
  pull_request:
    branches:
      - main
    paths:
      - "pulumi/resources/**"
      - "pulumi/package*.json"
      - "pulumi/tsconfig.json"
      - ".github/workflows/pulumi.yml"
  workflow_dispatch:
    inputs:
      stage:
        description: "Deployment stage"
        required: false
        default: "test"
        type: choice
        options:
          - common
          - test
          - prod
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.inputs.stage }}
  cancel-in-progress: true
jobs:
  pulumi:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: pulumi/package-lock.json
      - name: Install dependencies
        run: npm ci --ignore-scripts
        working-directory: ./pulumi
      - name: Run checks
        run: |
          npm run format
          npm run typecheck
        working-directory: ./pulumi
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@517a711dbcd0e402f90c77e7e2f81e849156e31d # v6.2.2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
      - name: Setup
        run: pulumi login ${{ env.PULUMI_BACKEND }}
        env:
          PULUMI_BACKEND: ${{ secrets.PULUMI_BACKEND }}
        working-directory: ./pulumi
      - name: Select stack ${{ github.event.inputs.stage || 'test' }}
        run: pulumi stack select ${{ env.STAGE }}
        env:
          STAGE: ${{ github.event.inputs.stage || 'test' }}
        working-directory: ./pulumi
      - name: Preview stack ${{ github.event.inputs.stage || 'test' }}
        run: pulumi refresh --preview-only
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
        working-directory: ./pulumi
