name: test
on:
  pull_request:
    branches: test
  workflow_dispatch:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      CSE_ID: ${{ secrets.CSE_ID }}
      GOOGLE_API: ${{ secrets.GOOGLE_API }}
      OPENWEATHER_API: ${{ secrets.OPENWEATHER_API }}
      REGION: FI
      ENVIRONMENT: test
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          pip install -r src/requirements.txt
      - name: Run tests
        run: python tests/runtests.py
